import Head from 'next/head';


import { Button, Card, Typography } from '@mui/material';
import Banner from '@/components/Banner';



export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner title='Arts Shaker' tagline='Client manager for artists'
        btn1={<Button variant='contained' className='rounded-lg'>Get Started</Button>}
        btn2={<Button variant='outlined' className='rounded-lg'>Tutorial</Button>}
        ></Banner>
      </main>
    </>
  );
}
